var allIcons = [
  { icon:"img/BNK.png" },
  { icon:"img/CNN.png" },
  { icon:"img/Drive.png" },
  { icon:"img/FreePress.png" },
  { icon:"img/GitHub.png" },
  { icon:"img/Google.png" },
  { icon:"img/Image.png" },
  { icon:"img/Indeed.png" },
  { icon:"img/Launch.png" },
  { icon:"img/Linked.png" },
  { icon:"img/Notes.png" },
  { icon:"img/ReadLater.png" },
  { icon:"img/RTorrent.png" },
  { icon:"img/Slack.png" },
  { icon:"img/Tape.png" },
  { icon:"img/Trend.png" },
  { icon:"img/Tube.png" },
  { icon:"img/Twitter.png" },
  { icon:"img/Wiki.png" }
];
