var defaultArray = [
  {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.google.com/",
    "icon": "img/ico/A001_Google.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.youtube.com/",
    "icon": "img/ico/A002_YouTube.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.facebook.com/",
    "icon": "img/ico/A003_Facebook.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.wikipedia.org/",
    "icon": "img/ico/A004_Wikipedia.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.reddit.com/",
    "icon": "img/ico/A005_Reddit.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.amazon.com/",
    "icon": "img/ico/A006_Amazon.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://twitter.com/",
    "icon": "img/ico/A007_Twitter.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.instagram.com/",
    "icon": "img/ico/A008_Instagram.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.linkedin.com/",
    "icon": "img/ico/A009_LinkedIn.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://getpocket.com/",
    "icon": "img/ico/A010_Pocket.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.netflix.com/",
    "icon": "img/ico/A011_Netflix.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.ebay.com/",
    "icon": "img/ico/A012_Ebay.png"
  }, {
    "type": "link-widget",
    "sizeX": 1,
    "sizeY": 1,
    "url": "https://www.twitch.tv/",
    "icon": "img/ico/A013_Twitch.png"
  }
];

module.exports.widgetString = JSON.stringify(defaultArray);

